name: Java Continuous Integration

on: [ pull_request ]

jobs:
  test_pull_request:
    name: JUnit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    # create lib/ directory
    - run: mkdir -p lib/
    # fetch jar file for junit
    - name: wget
      uses: wei/wget@v1
      with:
        # saving file to lib/ directory
        args: -O lib/junit.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar
    - run: mkdir -p temp/
    - run: javac -cp ".:java:lib/junit.jar:" -d temp/ src/transactions/*.java
    - run: java -cp java transactions.TransactionEngineTest